### ISSUE TITLE
Failed to build Jenkins Job

### ISSUE THREAD

**Issue by asherungar-ceva** [null511/Jenkins.NET#2]
Hi,

i'm trying to run a jenkins job using the build runner. 
i am getting exception "Failed to build Jenkins Job ... ".

the parameters of the jenkins client seem ok i added the URL, user and password needed.
i also added a dictionary with build parameters.
the same parameters work with the "jenkins-cli.jar" - 
is there anything i'm missing?

Thanks
Asher

**Comment by asherungar-ceva** [comment]
adding more information:
i've added the token= to the token of the build, and if i take the URL your build, copy paste it to chrome it succeeds, but for the httpWebrequest i get:
“The remote server returned an error: (403) Forbidden”

**Comment by null511** [comment]
My apologies, the documentation is a work-in-progress that doesn't get much attention. I'll finish updating the [Creating the Client](https://github.com/null511/Jenkins.NET/wiki/Creating-the-Client) Wiki page sometime today.

What was not documented is that you need to use the matching ApiToken of the user for the password, not the actual password.


```C#
var jenkinsClient = new JenkinsClient {
    BaseUrl = "http://localhost:8080",
    UserName = "admin",
    Password = "0123456789ABCDEF",
};
```

**Comment by asherungar-ceva** [comment]
Yes, that did it ☺

Thanks

Asher Ungar
Debugger Team Leader
SDT,        CEVA-DSP
