### ISSUE TITLE
Timeout occurred while waiting for build to complete!

### ISSUE THREAD

**Issue by asherungar-ceva** [null511/Jenkins.NET#3]
Hi,

trying to run with the build runner and getting:
Timeout occurred while waiting for build to complete!

my build is much longer than 60 seconds, and in fact i would just want to wait forever.
i tried setting "runner.BuildTimeout = -1;"
but still failed on that exception.

Thanks,
Asher

**Comment by null511** [comment]
There are two timeout properties exposed on the `JenkinsClient` instance:

#### `JenkinsClient.QueueTimeout`
> Gets or sets the maximum time in seconds to wait for job to be queued. Default value is 30.

The queue duration is the measurement of time between when the job is started by the user to when the job begins execution on the Jenkins node.

#### `JenkinsClient.BuildTimeout`
> Gets or sets the maximum time in seconds to wait for job to complete. Default value is 60.

The build timeout is the measurement of execution time for the current job, excluding the queue duration.

-----

Currently there is no 'unlimited' time option exposed by the Jenkins API (that I' aware of). Alternatively, you can specify very large values, such as `3600 = 1 hour` or `Int32.MaxValue = ~68 years`.

**Comment by null511** [comment]
I had not yet made coffee this morning when I replied. The timeout is within the `JenkinsClient` [here](https://github.com/null511/Jenkins.NET/blob/master/Jenkins.NET/JenkinsJobRunner.cs#L215). I will create an update shortly and publish the updated package.

**Comment by null511** [comment]
Fixed by PR #4 
Released in 0.1.7

**Comment by asherungar-ceva** [comment]
Don’t you mean the BuildTimeout in the “JenkinsJobRunner”?

For me:
var runner = new JenkinsJobRunner(client);
runner.BuildTimeout = Int32.MaxValue;

worked ..

Asher Ungar
Debugger Team Leader
SDT,        CEVA-DSP

**Comment by null511** [comment]
> Don’t you mean the BuildTimeout in the “JenkinsJobRunner”?

Yes I did. Comments have been updated.

> `runner.BuildTimeout = Int32.MaxValue;`

As of 0.1.7, you should be able to use `runner.BuildTimeout = 0;` to disable the timeout; though I still recommend setting a reasonable value instead.

**Comment by null511** [comment]
Closing as resolved, by release 0.1.7.
