### ISSUE TITLE
Q: is file parameter supported?

### ISSUE THREAD

**Issue by maulwuff** [null511/Jenkins.NET#34]
I'd like to know if this project supports passing a file parameter to jenkins?

**Comment by dnunez32** [comment]
It mentions it on the front page to use BuildWithParameters

**Comment by maulwuff** [comment]
In the meantime I came to the conclusion, it doesn't. Only string parameters are supported.
JenkinsWebApi supports both types.

**Comment by null511** [comment]
Job parameters are currently passed via query string, so larger content like file streams are **not** supported. If the Jenkins API supports multi-part content streams, then they are currently not supported by this library. I haven't used Jenkins in almost 5 years now, so there have not been any updates and little personal motivation to setup a Jenkins instance just to support this library.
